export const carouselData = [
  {
    title: ["SOCIAL", "MEDIA"],
    items: [
      {
        id: 1,
        src: "/images/dsmen/dsmenBranding1.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/images/dsmen/dsmenBranding2.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/images/dsmen/dsmenBranding4.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/images/dsmen/dsmenBranding5.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/images/dsmen/dsmenBranding7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["STREET", "STYLE"],

    items: [
      {
        id: 12,
        type: "video",
        src: "/images/dsmen/dsmenStreetstyleReel.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 11,
        src: "/images/dsmen/dsmenStreetstyle1.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 10,
        src: "/images/dsmen/dsmenStreetstyle2.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 9,
        type: "video",
        src: "/images/dsmen/dsmenStreetstyleReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 8,
        type: "video",
        src: "/images/dsmen/dsmenStreetstyleReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 1,
        src: "/images/dsmen/dsmenStreetstyle3.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/images/dsmen/dsmenStreetstyle4.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        type: "video",
        src: "/images/dsmen/dsmenStreetstyleReel4.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/images/dsmen/dsmenStreetstyleReel5.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/images/dsmen/dsmenStreetstyle5.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/images/dsmen/dsmenStreetstyle6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        type: "video",
        src: "/images/dsmen/dsmenStreetstyleReel6.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 8,
        src: "/images/dsmen/dsmenStreetstyle7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 9,
        src: "/images/dsmen/dsmenStreetstyle8.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 10,
        src: "/images/dsmen/dsmenStreetstyle9.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 11,
        src: "/images/dsmen/dsmenStreetstyle10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/images/dsmen/dsmenStreetstyle11.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["NAVIDAD", "2023"],
    items: [
      {
        id: 1,
        src: "/images/dsmen/dsmenNavidad1.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 2,
        src: "/images/dsmen/dsmenNavidad2.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 3,
        src: "/images/dsmen/dsmenNavidad3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 4,
        src: "/images/dsmen/dsmenNavidad4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 5,
        src: "/images/dsmen/dsmenNavidad5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/dsmen/dsmenNavidad6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/dsmen/dsmenNavidad7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/dsmen/dsmenNavidad8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/dsmen/dsmenNavidad9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["DSMEN", "SALE"],
    items: [
      {
        id: 1,
        src: "/images/dsmen/dsmenSale1.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/images/dsmen/dsmenSale2.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/images/dsmen/dsmenSale3.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/images/dsmen/dsmenSale4.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/images/dsmen/dsmenSale5.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/images/dsmen/dsmenSale6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/images/dsmen/dsmenSale7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
];
