export const carouselData = [
  {
    title: ["SOCIAL", "MEDIA"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/images/pucheta/puchetaReel.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/images/pucheta/puchetaReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/images/pucheta/puchetaStories.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/images/pucheta/puchetaReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/images/pucheta/puchetaStories2.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/pucheta/puchetaReel4.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/pucheta/puchetaStories3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/pucheta/puchetaReel5.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/pucheta/puchetaStories4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/images/pucheta/puchetaStories5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/images/pucheta/puchetaStories6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/images/pucheta/puchetaStories7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/images/pucheta/puchetaStories8.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/images/pucheta/puchetaStories9.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/images/pucheta/puchetaStories10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["INSTAGRAM", "FEED"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/images/pucheta/puchetaPost.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "image",
        src: "/images/pucheta/puchetaPost2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/images/pucheta/puchetaPost3.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "image",
        src: "/images/pucheta/puchetaPost4.webp",
        alt: "Solo Agency Reel",
      },
    ],
  },
  {
    title: ["PUCHETA", "ICONS"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/images/pucheta/puchetaIcons1.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "image",
        src: "/images/pucheta/puchetaIcons2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/images/pucheta/puchetaIcons3.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 11,
        src: "/images/pucheta/puchetaIcon1.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 4,
        type: "image",
        src: "/images/pucheta/puchetaIcons4.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/images/pucheta/puchetaIcons5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/pucheta/puchetaIcons6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },

      {
        id: 12,
        src: "/images/pucheta/puchetaIcon2.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/pucheta/puchetaIcons7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/pucheta/puchetaIcons8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/pucheta/puchetaIcons9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/images/pucheta/puchetaIcons10.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 13,
        src: "/images/pucheta/puchetaIcon3.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["MARTIN FIERRO", "RUNWAY"],

    items: [
      {
        id: 1,
        type: "image",
        src: "/images/pucheta/puchetaMartinFierro.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/images/pucheta/puchetaMartinFierroReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/images/pucheta/puchetaMartinFierro2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/images/pucheta/puchetaMartinFierroReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/images/pucheta/puchetaMartinFierro3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/pucheta/puchetaMartinFierro4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/pucheta/puchetaMartinFierroReel4.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/pucheta/puchetaMartinFierro5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/pucheta/puchetaMartinFierro6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/images/pucheta/puchetaMartinFierroReel5.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/images/pucheta/puchetaMartinFierro7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["E-", "COMMERCE"],
    items: [
      {
        id: 1,
        src: "/images/pucheta/puchetaEcom.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/images/pucheta/puchetaEcom2.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/images/pucheta/puchetaEcom3.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/images/pucheta/puchetaEcom4.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/images/pucheta/puchetaEcom5.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/images/pucheta/puchetaEcom6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/images/pucheta/puchetaEcom7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/images/pucheta/puchetaEcom8.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 9,
        src: "/images/pucheta/puchetaEcom9.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 10,
        src: "/images/pucheta/puchetaEcom10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 11,
        src: "/images/pucheta/puchetaEcom11.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/images/pucheta/puchetaEcom12.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/images/pucheta/puchetaEcom13.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/images/pucheta/puchetaEcom14.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/images/pucheta/puchetaEcom15.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 16,
        src: "/images/pucheta/puchetaEcom16.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 17,
        src: "/images/pucheta/puchetaEcom17.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["CAMPAÑA", "2023"],
    items: [
      {
        id: 1,
        src: "/images/pucheta/puchetaElementos1.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 2,
        src: "/images/pucheta/puchetaElementos2.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 3,
        src: "/images/pucheta/puchetaElementos3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 4,
        src: "/images/pucheta/puchetaElementos4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 5,
        src: "/images/pucheta/puchetaElementos5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/pucheta/puchetaElementos6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/pucheta/puchetaElementos7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/pucheta/puchetaElementos8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/pucheta/puchetaElementos9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/images/pucheta/puchetaElementos10.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/images/pucheta/puchetaElementos11.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 12,
        src: "/images/pucheta/puchetaElementos12.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["PUCHETA", "RESILIENCIA"],

    items: [
      {
        id: 1,
        type: "image",
        src: "/images/pucheta/puchetaResiliencia.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/images/pucheta/puchetaResiliencia.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/images/pucheta/puchetaResiliencia2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "image",
        src: "/images/pucheta/puchetaResiliencia3.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/images/pucheta/puchetaResiliencia4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/pucheta/puchetaResiliencia5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/pucheta/puchetaResiliencia6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/pucheta/puchetaResiliencia7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/pucheta/puchetaResiliencia8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/images/pucheta/puchetaResiliencia9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
];
