export const brands = [
  {
    name: "dollstore",
    imageLocationMobile: "/images/logos/dollstoreLogo.png",
    imageLocation: "/images/logos/home/dollstoreLogo.png",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Paid Media",
      "Creative Strategy",
      "3D Design",
    ],
    route: "clients/dollstore",
  },
  {
    name: "dsmen",
    imageLocationMobile: "/images/logos/dsmenLogo.png",
    imageLocation: "/images/logos/home/dsmenLogo.png",
    category: "Fashion",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/dsmen",
  },
  {
    name: "AIA",
    imageLocationMobile: "/images/logos/aiaLogo.png",
    imageLocation: "/images/logos/home/aiaLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/aia",
  },
  {
    name: "Thurman",
    imageLocationMobile: "/images/logos/thurmanLogo.png",
    imageLocation: "/images/logos/home/thurmanLogo.png",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Paid Media",
      "Creative Strategy",
      "Production & Styling",
    ],
    route: "/clients/thurman",
  },
  {
    name: "Cristho",
    imageLocationMobile: "/images/logos/cristhoLogo.png",
    imageLocation: "/images/logos/home/cristhoLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/cristho",
  },
  {
    name: "Justa Osadia",
    imageLocationMobile: "/images/logos/justaosadiaLogo.png",
    imageLocation: "/images/logos/home/justaosadiaLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/justaOsadia",
  },
  {
    name: "Pucheta",
    imageLocationMobile: "/images/logos/puchetaLogo.png",
    imageLocation: "/images/logos/home/puchetaLogo.png",
    category: "Fashion",
    services: ["Content", "Social Media", "Creative Strategy"],
    route: "/clients/pucheta",
  },
  {
    name: "UBK",
    imageLocationMobile: "/images/logos/ubkLogo.png",
    imageLocation: "/images/logos/home/ubkLogo.png",
    category: "Lifestyle",
    services: ["Content", "Production & Styling"],
    route: "/clients/ubk",
  },
  {
    name: "Pimux",
    imageLocationMobile: "/images/logos/pimuxLogo.webp",
    imageLocation: "/images/logos/home/pimuxLogo.webp",
    category: "Lifestyle",
    services: ["Graphic Design & Branding"],
    route: "/clients/pimux",
  },
  {
    name: "Faitful",
    imageLocationMobile: "/images/logos/faitfulLogo.png",
    imageLocation: "/images/logos/home/faitfulLogo.png",
    category: "Lifestyle",
    services: ["Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/faitful",
  },
  {
    name: "Fernando Ramos",
    imageLocationMobile: "/images/logos/fernandoRamosLogo.png",
    imageLocation: "/images/logos/home/fernandoRamosLogo.png",
    category: "Lifestyle",
    services: ["Graphic Design & Branding"],
    route: "/clients/fernandoRamos",
  },
  {
    name: "El Gourmet",
    imageLocationMobile: "/images/logos/elgourmetLogo.png",
    imageLocation: "/images/logos/home/elgourmetLogo.png",
    category: "Food & other pleasures",
    services: ["Content", "Creative Strategy"],
    route: "/clients/elGourmet",
  },
  {
    name: "Dr Aromas",
    imageLocationMobile: "/images/logos/doctoraromasLogo.png",
    imageLocation: "/images/logos/home/doctoraromasLogo.png",
    category: "Lifestyle",
    services: ["Content"],
    route: "/clients/drAromas",
  },
  {
    name: "DA Design",
    imageLocationMobile: "/images/logos/dadesignLogo.png",
    imageLocation: "/images/logos/home/dadesignLogo.png",
    category: "Lifestyle",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/daDesign",
  },
  {
    name: "Compañia Nativa",
    imageLocationMobile: "/images/logos/companianativaLogo.png",
    imageLocation: "/images/logos/home/companianativaLogo.png",
    category: "Lifestyle",
    services: ["Content"],
    route: "/clients/companiaNativa",
  },
  {
    name: "Terrazas de los Andes",
    imageLocationMobile: "/images/logos/terrazasdelosandesLogo.png",
    imageLocation: "/images/logos/home/terrazasdelosandesLogo.png",
    category: "Food & other pleasures",
    services: ["Content"],
    route: "/clients/terrazas",
  },
  {
    name: "Lagouarde Catering",
    imageLocationMobile: "/images/logos/lagouardeLogo.png",
    imageLocation: "/images/logos/home/lagouardeLogo.png",
    category: "Food & other pleasures",
    services: [
      "Content",
      "Social Media",
      "Graphic Design & Branding",
      "Creative Strategy",
    ],
    route: "/clients/lagouardeCatering",
  },
  {
    name: "Celebre in culina",
    imageLocationMobile: "/images/logos/celebreinculinaLogo.png",
    imageLocation: "/images/logos/home/celebreinculinaLogo.png",
    category: "Food & other pleasures",
    services: ["Content"],
    route: "/clients/celebreInCulina",
  },
  {
    name: "Timeless",
    imageLocationMobile: "/images/logos/timelessLogo.webp",
    imageLocation: "/images/logos/home/timelessLogo.webp",
    category: "Health & beauty",
    services: ["Graphic Design & Branding"],
    route: "/clients/timeless",
  },
  {
    name: "Lidherma",
    imageLocationMobile: "/images/logos/lidhermaLogo.png",
    imageLocation: "/images/logos/home/lidhermaLogo.png",
    category: "Health & beauty",
    services: ["Content"],
    route: "/clients/lidherma",
  },
  {
    name: "Eucerin",
    imageLocationMobile: "/images/logos/eucerinLogo.png",
    imageLocation: "/images/logos/home/eucerinLogo.png",
    category: "Health & beauty",
    services: ["Content"],
    route: "/clients/eucerin",
  },
  {
    name: "Sassone",
    imageLocationMobile: "/images/logos/sassoneLogo.webp",
    imageLocation: "/images/logos/home/sassoneLogo.webp",
    category: "Lifestyle",
    services: ["Content", "Graphic Design & Branding"],
    route: "/clients/sassone",
  },
];
