export const brands = [
  {
    name: "dollstore",
    imageLocation: "/logos/dollstoreLogo.png",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Paid Media",
      "Creative Strategy",
      "3D Design",
    ],
    route: "clients/dollstore",
  },
  {
    name: "dsmen",
    imageLocation: "/logos/dsmenLogo.png",
    category: "Fashion",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/dsmen",
  },
  {
    name: "AIA",
    imageLocation: "/logos/aiaLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/aia",
  },
  {
    name: "Thurman",
    imageLocation: "/logos/thurmanLogo.png",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Paid Media",
      "Creative Strategy",
      "Production & Styling",
    ],
    route: "/clients/thurman",
  },
  {
    name: "Cape Diablo",
    imageLocation: "/logos/capediabloLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/capeDiablo",
  },
  {
    name: "Cristho",
    imageLocation: "/logos/cristhoLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/cristho",
  },
  {
    name: "Justa Osadia",
    imageLocation: "/logos/justaosadiaLogo.png",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/justaOsadia",
  },
  {
    name: "Pucheta",
    imageLocation: "/logos/puchetaLogo.png",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Graphic Design & Branding",
      "Creative Strategy",
    ],
    route: "/clients/pucheta",
  },
  {
    name: "HiSilvie",
    imageLocation: "/logos/hisilvieLogo.png",
    category: "Fashion",
    services: ["Content", "Production & Styling", "Creative Strategy"],
    route: "/clients/hiSilvie",
  },
  {
    name: "UBK",
    imageLocation: "/logos/ubkLogo.png",
    category: "Lifestyle",
    services: ["Content", "Production & Styling"],
    route: "/clients/ubk",
  },
  {
    name: "Pimux",
    imageLocation: "/logos/pimuxLogo.png",
    category: "Lifestyle",
    services: ["Graphic Design & Branding"],
    route: "/clients/pimux",
  },
  {
    name: "Lagouarde",
    imageLocation: "/logos/lagouardeLogo.png",
    category: "Lifestyle",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/lagouardePropiedades",
  },
  {
    name: "Faitful",
    imageLocation: "/logos/faitfulLogo.png",
    category: "Lifestyle",
    services: ["Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/faitful",
  },
  {
    name: "El Gourmet",
    imageLocation: "/logos/elgourmetLogo.png",
    category: "Lifestyle",
    services: ["Content", "Creative Strategy"],
    route: "/clients/elGourmet",
  },
  {
    name: "Dr Aromas",
    imageLocation: "/logos/doctoraromasLogo.png",
    category: "Lifestyle",
    services: ["Content"],
    route: "/clients/drAromas",
  },
  {
    name: "DA Design",
    imageLocation: "/logos/dadesignLogo.png",
    category: "Lifestyle",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/daDesign",
  },
  {
    name: "Compañia Nativa",
    imageLocation: "/logos/companianativaLogo.png",
    category: "Lifestyle",
    services: ["Content"],
    route: "/clients/companiaNativa",
  },
  {
    name: "Terrazas de los Andes",
    imageLocation: "/logos/terrazasdelosandesLogo.png",
    category: "Food & other pleasures",
    services: ["Content"],
    route: "/clients/terrazas",
  },
  {
    name: "Lagouarde Catering",
    imageLocation: "/logos/lagouardeLogo.png",
    category: "Food & other pleasures",
    services: [
      "Content",
      "Social Media",
      "Graphic Design & Branding",
      "Creative Strategy",
    ],
    route: "/clients/lagouardeCatering",
  },
  {
    name: "Celebre in culina",
    imageLocation: "/logos/celebreinculinaLogo.png",
    category: "Food & other pleasures",
    services: ["Content"],
    route: "/clients/celebreInCulina",
  },
  {
    name: "Yellow",
    imageLocation: "/logos/yellowLogo.png",
    category: "Health & beauty",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/yellow",
  },
  {
    name: "Timeless",
    imageLocation: "/logos/timelessLogo.png",
    category: "Health & beauty",
    services: ["Graphic Design & Branding"],
    route: "/clients/timeless",
  },
  {
    name: "Lidherma",
    imageLocation: "/logos/lidhermaLogo.png",
    category: "Health & beauty",
    services: ["Content"],
    route: "/clients/lidherma",
  },
  {
    name: "JP Peluquerias",
    imageLocation: "/logos/jpLogo.png",
    category: "Health & beauty",
    services: [
      "Content",
      "Social Media",
      "Creative Strategy",
      "Production & Styling",
    ],
    route: "/clients/jp",
  },
  {
    name: "Eucerin",
    imageLocation: "/logos/eucerinLogo.png",
    category: "Health & beauty",
    services: ["Content"],
    route: "/clients/eucerin",
  },
  {
    name: "Sassone",
    imageLocation: "/logos/sassoneLogo.png",
    category: "Lifestyle",
    services: ["Content", "Graphic Design & Branding"],
    route: "/clients/sassone",
  },
];
