export const brands = [
  {
    name: "dollstore",
    imageLocation: "/images/logos/dollstoreLogo.webp",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Paid Media",
      "Creative Strategy",
      "3D Design",
    ],
    route: "clients/dollstore",
  },
  {
    name: "dsmen",
    imageLocation: "/images/logos/dsmenLogo.webp",
    category: "Fashion",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/dsmen",
  },
  {
    name: "AIA",
    imageLocation: "/images/logos/aiaLogo.webp",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/aia",
  },
  {
    name: "Thurman",
    imageLocation: "/images/logos/thurmanLogo.webp",
    category: "Fashion",
    services: [
      "Content",
      "Social Media",
      "Paid Media",
      "Creative Strategy",
      "Production & Styling",
    ],
    route: "/clients/thurman",
  },
  {
    name: "Cristho",
    imageLocation: "/images/logos/cristhoLogo.webp",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/cristho",
  },
  {
    name: "Justa Osadia",
    imageLocation: "/images/logos/justaosadiaLogo.webp",
    category: "Fashion",
    services: ["Content"],
    route: "/clients/justaOsadia",
  },
  {
    name: "Pucheta",
    imageLocation: "/images/logos/puchetaLogo.webp",
    category: "Fashion",
    services: ["Content", "Social Media", "Creative Strategy"],
    route: "/clients/pucheta",
  },
  {
    name: "UBK",
    imageLocation: "/images/logos/ubkLogo.webp",
    category: "Lifestyle",
    services: ["Content", "Production & Styling"],
    route: "/clients/ubk",
  },
  {
    name: "Pimux",
    imageLocation: "/images/logos/pimuxLogo.webp",
    category: "Lifestyle",
    services: ["Graphic Design & Branding"],
    route: "/clients/pimux",
  },
  {
    name: "Faitful",
    imageLocation: "/images/logos/faitfulLogo.webp",
    category: "Lifestyle",
    services: ["Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/faitful",
  },
  {
    name: "Fernando Ramos",
    imageLocation: "/images/logos/fernandoRamosLogo.webp",
    category: "Lifestyle",
    services: ["Graphic Design & Branding"],
    route: "/clients/fernandoRamos",
  },
  {
    name: "El Gourmet",
    imageLocation: "/images/logos/elgourmetLogo.webp",
    category: "Food & other pleasures",
    services: ["Content", "Creative Strategy"],
    route: "/clients/elGourmet",
  },
  {
    name: "Dr Aromas",
    imageLocation: "/images/logos/doctoraromasLogo.webp",
    category: "Lifestyle",
    services: ["Content"],
    route: "/clients/drAromas",
  },
  {
    name: "DA Design",
    imageLocation: "/images/logos/dadesignLogo.webp",
    category: "Lifestyle",
    services: ["Content", "Social Media", "Paid Media", "Creative Strategy"],
    route: "/clients/daDesign",
  },
  {
    name: "Compañia Nativa",
    imageLocation: "/images/logos/companianativaLogo.webp",
    category: "Lifestyle",
    services: ["Content"],
    route: "/clients/companiaNativa",
  },
  {
    name: "Terrazas de los Andes",
    imageLocation: "/images/logos/terrazasdelosandesLogo.webp",
    category: "Food & other pleasures",
    services: ["Content"],
    route: "/clients/terrazas",
  },
  {
    name: "Lagouarde Catering",
    imageLocation: "/images/logos/lagouardeLogo.webp",
    category: "Food & other pleasures",
    services: [
      "Content",
      "Social Media",
      "Graphic Design & Branding",
      "Creative Strategy",
    ],
    route: "/clients/lagouardeCatering",
  },
  {
    name: "Celebre in culina",
    imageLocation: "/images/logos/celebreinculinaLogo.webp",
    category: "Food & other pleasures",
    services: ["Content"],
    route: "/clients/celebreInCulina",
  },
  {
    name: "Timeless",
    imageLocation: "/images/logos/timelessLogo.webp",
    category: "Health & beauty",
    services: ["Graphic Design & Branding"],
    route: "/clients/timeless",
  },
  {
    name: "Lidherma",
    imageLocation: "/images/logos/lidhermaLogo.webp",
    category: "Health & beauty",
    services: ["Content"],
    route: "/clients/lidherma",
  },
  {
    name: "Eucerin",
    imageLocation: "/images/logos/eucerinLogo.webp",
    category: "Health & beauty",
    services: ["Content"],
    route: "/clients/eucerin",
  },
  {
    name: "Sassone",
    imageLocation: "/images/logos/sassoneLogo.webp",
    category: "Lifestyle",
    services: ["Content", "Graphic Design & Branding"],
    route: "/clients/sassone",
  },
];
