export const carouselData = [
  {
    title: ["INSTAGRAM", "STORIES"],
    items: [
      {
        id: 1,
        src: "/images/daDesign/daDesignHistorias1.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/images/daDesign/daDesignHistorias2.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/images/daDesign/daDesignHistorias3.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/images/daDesign/daDesignHistorias4.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/images/daDesign/daDesignHistorias5.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/images/daDesign/daDesignHistorias6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/images/daDesign/daDesignHistorias7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/images/daDesign/daDesignHistorias8.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 9,
        src: "/images/daDesign/daDesignHistorias9.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 10,
        src: "/images/daDesign/daDesignHistorias10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 11,
        src: "/images/daDesign/daDesignHistorias11.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/images/daDesign/daDesignHistorias12.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/images/daDesign/daDesignHistorias13.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/images/daDesign/daDesignHistorias14.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/images/daDesign/daDesignHistorias15.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 16,
        src: "/images/daDesign/daDesignHistorias16.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 17,
        src: "/images/daDesign/daDesignHistorias17.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 18,
        src: "/images/daDesign/daDesignHistorias18.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 19,
        src: "/images/daDesign/daDesignHistorias19.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 20,
        src: "/images/daDesign/daDesignHistorias20.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 21,
        src: "/images/daDesign/daDesignHistorias21.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 22,
        src: "/images/daDesign/daDesignHistorias22.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["INSTAGRAM", "FEED"],
    items: [
      {
        id: 1,
        src: "/images/daDesign/daDesign1.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 2,
        src: "/images/daDesign/daDesign2.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 3,
        src: "/images/daDesign/daDesign3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 4,
        src: "/images/daDesign/daDesign4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 5,
        src: "/images/daDesign/daDesign5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/images/daDesign/daDesign6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/images/daDesign/daDesign7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/images/daDesign/daDesign8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/images/daDesign/daDesign9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/images/daDesign/daDesign10.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/images/daDesign/daDesign11.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 12,
        src: "/images/daDesign/daDesign12.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 13,
        src: "/images/daDesign/daDesign13.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 14,
        src: "/images/daDesign/daDesign14.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 15,
        src: "/images/daDesign/daDesign15.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 16,
        src: "/images/daDesign/daDesign16.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 17,
        src: "/images/daDesign/daDesign17.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 18,
        src: "/images/daDesign/daDesign18.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 19,
        src: "/images/daDesign/daDesign19.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["INSTAGRAM", "REELS"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/images/daDesign/daDesignReel.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/images/daDesign/daDesignReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "video",
        src: "/images/daDesign/daDesignReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/images/daDesign/daDesignReel4.webm",
        alt: "Solo Agency Reel",
      },
    ],
  },
];
