export const carouselData = [
  {
    title: ["HYDRO", "FLUID"],
    hideLastItems: [16],
    items: [
      {
        id: 3,
        type: "video",
        src: "/images/eucerin/eucerinVideo2.webm",
        alt: "Eucerin Media",
      },
      {
        id: 4,
        type: "image",
        src: "/images/eucerin/Eucerin1.webp",
        alt: "Eucerin Media",
      },
      {
        id: 6,
        type: "image",
        src: "/images/eucerin/Eucerin2.webp",
        alt: "Eucerin Media",
      },
      {
        id: 5,
        type: "video",
        src: "/images/eucerin/eucerinVideo.webm",
        alt: "Eucerin Media",
      },
      {
        id: 7,
        type: "video",
        src: "/images/eucerin/eucerinVideo3.webm",
        alt: "Eucerin Media",
      },
      {
        id: 12,
        type: "image",
        src: "/images/eucerin/Eucerin7.webp",
        alt: "Eucerin Media",
      },
      {
        id: 16,
        type: "image",
        src: "/images/eucerin/Eucerin11.webp",
        alt: "Eucerin Media",
      },
      {
        id: 17,
        type: "image",
        src: "/images/eucerin/Eucerin12.webp",
        alt: "Eucerin Media",
      },
      {
        id: 18,
        type: "image",
        src: "/images/eucerin/Eucerin13.webp",
        alt: "Eucerin Media",
      },
      {
        id: 19,
        type: "image",
        src: "/images/eucerin/Eucerin14.webp",
        alt: "Eucerin Media",
      },
      {
        id: 20,
        type: "image",
        src: "/images/eucerin/Eucerin15.webp",
        alt: "Eucerin Media",
      },
      {
        id: 21,
        type: "image",
        src: "/images/eucerin/Eucerin16.webp",
        alt: "Eucerin Media",
      },
      {
        id: 22,
        type: "image",
        src: "/images/eucerin/Eucerin17.webp",
        alt: "Eucerin Media",
      },
      {
        id: 23,
        type: "image",
        src: "/images/eucerin/Eucerin18.webp",
        alt: "Eucerin Media",
      },
      {
        id: 25,
        type: "image",
        src: "/images/eucerin/Eucerin20.webp",
        alt: "Eucerin Media",
      },
      {
        id: 29,
        type: "image",
        src: "/images/eucerin/Eucerin24.webp",
        alt: "Eucerin Media",
      },
      {
        id: 27,
        type: "image",
        src: "/images/eucerin/Eucerin22.webp",
        alt: "Eucerin Media",
      },
    ],
  },
];
