export const clientLogos = [
  { href: "../clients/elGorumet", logo: "/logos/elgourmetLogo.webp" },
  { href: "../clients/dollstore", logo: "/logos/dollstoreLogo.webp" },
  { href: "../clients/eucerin", logo: "/logos/eucerinLogo.webp" },
  { href: "../clients/justaOsadia", logo: "/logos/justaosadiaLogo.webp" },
  { href: "../clients/lidherma", logo: "/logos/lidhermaLogo.webp" },
  { href: "../clients/pucheta", logo: "/logos/puchetaLogo.webp" },
  { href: "../clients/elGorumet", logo: "/logos/elgourmetLogo.webp" },
  { href: "../clients/dollstore", logo: "/logos/dollstoreLogo.webp" },
  { href: "../clients/eucerin", logo: "/logos/eucerinLogo.webp" },
  { href: "../clients/justaOsadia", logo: "/logos/justaosadiaLogo.webp" },
  { href: "../clients/lidherma", logo: "/logos/lidhermaLogo.webp" },
  { href: "../clients/pucheta", logo: "/logos/puchetaLogo.webp" },
  { href: "../clients/elGorumet", logo: "/logos/elgourmetLogo.webp" },
  { href: "../clients/dollstore", logo: "/logos/dollstoreLogo.webp" },
  { href: "../clients/eucerin", logo: "/logos/eucerinLogo.webp" },
  { href: "../clients/justaOsadia", logo: "/logos/justaosadiaLogo.webp" },
  { href: "../clients/lidherma", logo: "/logos/lidhermaLogo.webp" },
  { href: "../clients/pucheta", logo: "/logos/puchetaLogo.webp" },
];
