export const carouselData = [
  {
    title: ["E-", "COMMERCE"],
    items: [
      {
        id: 1,
        src: "/pucheta/puchetaEcom.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/pucheta/puchetaEcom2.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/pucheta/puchetaEcom3.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/pucheta/puchetaEcom4.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/pucheta/puchetaEcom5.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/pucheta/puchetaEcom6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/pucheta/puchetaEcom7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/pucheta/puchetaEcom8.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["", ""],
    items: [
      {
        id: 9,
        src: "/pucheta/puchetaEcom9.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 10,
        src: "/pucheta/puchetaEcom10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 11,
        src: "/pucheta/puchetaEcom11.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/pucheta/puchetaEcom12.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/pucheta/puchetaEcom13.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/pucheta/puchetaEcom14.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/pucheta/puchetaEcom15.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 16,
        src: "/pucheta/puchetaEcom16.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 17,
        src: "/pucheta/puchetaEcom17.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["CAMPAÑA", "ELEMENTOS"],
    items: [
      {
        id: 1,
        src: "/pucheta/puchetaElementos1.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 2,
        src: "/pucheta/puchetaElementos2.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 3,
        src: "/pucheta/puchetaElementos3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 4,
        src: "/pucheta/puchetaElementos4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 5,
        src: "/pucheta/puchetaElementos5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaElementos6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaElementos7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaElementos8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaElementos9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaElementos10.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/pucheta/puchetaElementos11.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 12,
        src: "/pucheta/puchetaElementos12.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["PUCHETA", "ICONS"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaIcons1.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "image",
        src: "/pucheta/puchetaIcons2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaIcons3.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "image",
        src: "/pucheta/puchetaIcons4.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaIcons5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaIcons6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaIcons7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaIcons8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaIcons9.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaIcons10.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["SOCIAL", "MEDIA"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/pucheta/puchetaReel.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/pucheta/puchetaReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaStories.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/pucheta/puchetaReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaStories2.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaReel4.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaStories3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaReel5.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaStories4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaStories5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/pucheta/puchetaStories6.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/pucheta/puchetaStories7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/pucheta/puchetaStories8.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/pucheta/puchetaStories9.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/pucheta/puchetaStories10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["INSTAGRAM", "FEED"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaPost.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "image",
        src: "/pucheta/puchetaPost2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaPost3.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "image",
        src: "/pucheta/puchetaPost4.webp",
        alt: "Solo Agency Reel",
      },
    ],
  },
  {
    title: ["MARTIN FIERRO", "RUNWAY"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaMartinFierro.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/pucheta/puchetaMartinFierroReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaMartinFierro2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/pucheta/puchetaMartinFierroReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaMartinFierro3.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaMartinFierro4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaMartinFierroReel4.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaMartinFierro5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaMartinFierro6.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaMartinFierroReel5.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/pucheta/puchetaMartinFierro7.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["PUCHETA", "RESILIENCIA"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaResiliencia.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/pucheta/puchetaResiliencia.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaResiliencia2.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/pucheta/puchetaResiliencia3.webp",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaResiliencia4.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaResiliencia5.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaResiliencia6.webp",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaResiliencia7.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaResiliencia8.webp",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaResiliencia9.webp",
        type: "video",
        alt: "Solo Agency Feed",
      },
    ],
  },
];
