export const carouselData = [
  {
    title: ["E-", "COMMERCE"],
    items: [
      {
        id: 1,
        src: "/pucheta/puchetaEcom.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/pucheta/puchetaEcom2.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/pucheta/puchetaEcom3.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/pucheta/puchetaEcom4.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/pucheta/puchetaEcom5.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/pucheta/puchetaEcom6.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/pucheta/puchetaEcom7.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/pucheta/puchetaEcom8.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["", ""],
    items: [
      {
        id: 9,
        src: "/pucheta/puchetaEcom9.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 10,
        src: "/pucheta/puchetaEcom10.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 11,
        src: "/pucheta/puchetaEcom11.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/pucheta/puchetaEcom12.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/pucheta/puchetaEcom13.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/pucheta/puchetaEcom14.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/pucheta/puchetaEcom15.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 16,
        src: "/pucheta/puchetaEcom16.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 17,
        src: "/pucheta/puchetaEcom17.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["CAMPAÑA", "ELEMENTOS"],
    items: [
      {
        id: 1,
        src: "/pucheta/puchetaElementos1.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 2,
        src: "/pucheta/puchetaElementos2.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 3,
        src: "/pucheta/puchetaElementos3.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 4,
        src: "/pucheta/puchetaElementos4.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 5,
        src: "/pucheta/puchetaElementos5.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaElementos6.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaElementos7.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaElementos8.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaElementos9.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaElementos10.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/pucheta/puchetaElementos11.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 12,
        src: "/pucheta/puchetaElementos12.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["PUCHETA", "ICONS"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaIcons1.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "image",
        src: "/pucheta/puchetaIcons2.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaIcons3.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "image",
        src: "/pucheta/puchetaIcons4.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaIcons5.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaIcons6.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaIcons7.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaIcons8.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaIcons9.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaIcons10.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
    ],
  },
  {
    title: ["SOCIAL", "MEDIA"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/pucheta/puchetaReel.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/pucheta/puchetaReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaStories.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/pucheta/puchetaReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaStories2.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaReel4.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaStories3.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaReel5.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaStories4.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaStories5.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/pucheta/puchetaStories6.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 12,
        src: "/pucheta/puchetaStories7.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 13,
        src: "/pucheta/puchetaStories8.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 14,
        src: "/pucheta/puchetaStories9.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 15,
        src: "/pucheta/puchetaStories10.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["INSTAGRAM", "FEED"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaPost.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "image",
        src: "/pucheta/puchetaPost2.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaPost3.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "image",
        src: "/pucheta/puchetaPost4.jpg",
        alt: "Solo Agency Reel",
      },
    ],
  },
  {
    title: ["MARTIN FIERRO", "RUNWAY"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaMartinFierro.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/pucheta/puchetaMartinFierroReel2.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaMartinFierro2.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/pucheta/puchetaMartinFierroReel3.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaMartinFierro3.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaMartinFierro4.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaMartinFierroReel4.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaMartinFierro5.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaMartinFierro6.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaMartinFierroReel5.webm",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 11,
        src: "/pucheta/puchetaMartinFierro7.jpg",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["PUCHETA", "RESILIENCIA"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/pucheta/puchetaResiliencia.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 2,
        type: "video",
        src: "/pucheta/puchetaResiliencia.webm",
        alt: "Solo Agency Reel",
      },
      {
        id: 3,
        type: "image",
        src: "/pucheta/puchetaResiliencia2.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 4,
        type: "video",
        src: "/pucheta/puchetaResiliencia3.jpg",
        alt: "Solo Agency Reel",
      },
      {
        id: 5,
        src: "/pucheta/puchetaResiliencia4.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 6,
        src: "/pucheta/puchetaResiliencia5.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 7,
        src: "/pucheta/puchetaResiliencia6.jpg",
        type: "video",
        alt: "Solo Agency Feed",
      },
      {
        id: 8,
        src: "/pucheta/puchetaResiliencia7.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 9,
        src: "/pucheta/puchetaResiliencia8.jpg",
        type: "image",
        alt: "Solo Agency Feed",
      },
      {
        id: 10,
        src: "/pucheta/puchetaResiliencia9.jpg",
        type: "video",
        alt: "Solo Agency Feed",
      },
    ],
  },
];
