export const gridData = [
  {
    title: ["INSTAGRAM", "FEED"],
    items: [
      { columns: 2 },
      {
        id: 1,
        src: "/lagouardePropiedades/feed_lagouarde_feb-05.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/lagouardePropiedades/feed_lagouarde_feb-10.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/lagouardePropiedades/feed_lagouarde_feb-11.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/lagouardePropiedades/feed_lagouarde_feb-18.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 1,
        src: "/lagouardePropiedades/feed_lagouarde_feb-19.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/lagouardePropiedades/feed_lagouarde_feb-20.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/lagouardePropiedades/feed_lagouarde_feb-21.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 1,
        src: "/lagouardePropiedades/feed_lagouarde_feb-23.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/lagouardePropiedades/feed_lagouarde_feb-24.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/lagouardePropiedades/feed_lagouarde_feb-38.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/lagouardePropiedades/feed_lagouarde_feb-39.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 1,
        src: "/lagouardePropiedades/feed_lagouarde_feb-40.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 3,
        src: "/lagouardePropiedades/feed_lagouarde_feb-42.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/lagouardePropiedades/feed_lagouarde_feb-43.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/lagouardePropiedades/Sin título-2-02.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/lagouardePropiedades/Sin título-2-03.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["INSTAGRAM", "STORIES"],
    items: [
      {
        id: 2,
        src: "/lagouardePropiedades/Historia13.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/lagouardePropiedades/Historia14.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/lagouardePropiedades/Historia22.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/lagouardePropiedades/Historia23.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 4,
        src: "/lagouardePropiedades/Historia24.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/lagouardePropiedades/Historia31.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/lagouardePropiedades/Historia32.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/lagouardePropiedades/Historia33.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
  {
    title: ["", ""],
    items: [
      {
        id: 4,
        src: "/lagouardePropiedades/Historia34.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/lagouardePropiedades/Historia42.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 2,
        src: "/lagouardePropiedades/Historia43.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 5,
        src: "/lagouardePropiedades/Historia11.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 7,
        src: "/lagouardePropiedades/Historia12.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 6,
        src: "/lagouardePropiedades/Screenshot 2024-04-24 at 11.32.51 AM.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
      {
        id: 8,
        src: "/lagouardePropiedades/Screenshot 2024-04-24 at 11.33.06 AM.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },

      {
        id: 4,
        src: "/lagouardePropiedades/Screenshot 2024-04-24 at 11.32.30 AM.webp",
        type: "image",
        alt: "Solo Agency Stories",
      },
    ],
  },
];
