export const gridData = [
  {
    title: ["SUMMER", "2024"],
    maxHeight: "475px",
    items: [
      {
        id: 1,
        type: "video",
        src: "/aia/aiaLycraVision.webm",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 10,
        type: "image",
        src: "/aia/aiaSummer7.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 11,
        type: "image",
        src: "/aia/aiaSummer8.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 2,
        type: "image",
        src: "/aia/aiaSummer1.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 3,
        type: "image",
        src: "/aia/aiaSummer2.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 4,
        type: "image",
        src: "/aia/aiaSummer3.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 5,
        type: "image",
        src: "/aia/aiaSummer4.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 7,
        type: "video",
        src: "/aia/aiaReel.webm",
        alt: "AIA Athleisure Wear Video",
      },
      {
        id: 12,
        type: "video",
        src: "/aia/aiaBatallaDeTenis.webm",
        alt: "AIA Tennis Battle Video",
      },
      {
        id: 8,
        type: "image",
        src: "/aia/aiaSummer5.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 9,
        type: "image",
        src: "/aia/aiaSummer6.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 16,
        type: "image",
        src: "/aia/aiaSummer11.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 17,
        type: "image",
        src: "/aia/aiaSummer12.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 18,
        type: "image",
        src: "/aia/aiaSummer13.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 19,
        type: "image",
        src: "/aia/aiaSummer14.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 13,
        type: "video",
        src: "/aia/aiaJogginConMusculosa.webm",
        alt: "AIA Jogging with Tank Top Video",
      },
      {
        id: 20,
        type: "image",
        src: "/aia/aiaSummer15.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 21,
        type: "image",
        src: "/aia/aiaSummer16.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 22,
        type: "image",
        src: "/aia/aiaSummer17.webp",
        alt: "AIA Be Free Be AIA Video",
      },
      {
        id: 23,
        type: "image",
        src: "/aia/aiaSummer18.webp",
        alt: "AIA Be Free Be AIA Video",
      },
    ],
  },
];
