export const carouselData = [
  {
    title: ["CREATIVE", "STRATEGY"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/jp/jpSocial7.webp",
        alt: "AIA Be Free Be AIA image",
      },
      {
        id: 2,
        type: "image",
        src: "/jp/jpSocial1.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 4,
        type: "image",
        src: "/jp/jpSocial2.webp",
        alt: "AIA Athleisure Wear image",
      },
      {
        id: 3,
        type: "image",
        src: "/jp/jpContent1.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 5,
        type: "image",
        src: "/jp/jpContent2.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 6,
        type: "image",
        src: "/jp/jpSocial3.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 7,
        type: "image",
        src: "/jp/jpContent3.webp",
        alt: "AIA Be Free Be AIA image",
      },
      {
        id: 8,
        type: "image",
        src: "/jp/jpSocial4.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 9,
        type: "image",
        src: "/jp/jpContent4.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 10,
        type: "image",
        src: "/jp/jpSocial5.webp",
        alt: "AIA Jogging with Tank Top image",
      },
      {
        id: 11,
        type: "image",
        src: "/jp/jpContent5.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 12,
        type: "image",
        src: "/jp/jpSocial6.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 13,
        type: "image",
        src: "/jp/jpContent6.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 15,
        type: "image",
        src: "/jp/jpContent7.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 16,
        type: "image",
        src: "/jp/jpContent8.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 17,
        type: "image",
        src: "/jp/jpContent9.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 18,
        type: "image",
        src: "/jp/jpContent10.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 19,
        type: "image",
        src: "/jp/jpContent11.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 20,
        type: "image",
        src: "/jp/jpContent12.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 21,
        type: "image",
        src: "/jp/jpContent13.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 22,
        type: "image",
        src: "/jp/jpContent14.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 23,
        type: "image",
        src: "/jp/jpContent15.webp",
        alt: "AIA Athleisure Wear",
      },
      {
        id: 24,
        type: "image",
        src: "/jp/jpContent16.webp",
        alt: "AIA Athleisure Wear",
      },
    ],
  },
];
