export const carouselData = [
    {
      title: ["INSTAGRAM", "STORIES"],
      items: [
        {
          id: 1,
          src: "/daDesign/daDesignHistorias1.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 2,
          src: "/daDesign/daDesignHistorias2.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 3,
          src: "/daDesign/daDesignHistorias3.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 4,
          src: "/daDesign/daDesignHistorias4.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 5,
          src: "/daDesign/daDesignHistorias5.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 6,
          src: "/daDesign/daDesignHistorias6.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 7,
          src: "/daDesign/daDesignHistorias7.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 8,
          src: "/daDesign/daDesignHistorias8.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 9,
          src: "/daDesign/daDesignHistorias9.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 10,
          src: "/daDesign/daDesignHistorias10.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 11,
          src: "/daDesign/daDesignHistorias11.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 12,
          src: "/daDesign/daDesignHistorias12.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 13,
          src: "/daDesign/daDesignHistorias13.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 14,
          src: "/daDesign/daDesignHistorias14.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 15,
          src: "/daDesign/daDesignHistorias15.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 16,
          src: "/daDesign/daDesignHistorias16.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 17,
          src: "/daDesign/daDesignHistorias17.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 18,
          src: "/daDesign/daDesignHistorias18.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 19,
          src: "/daDesign/daDesignHistorias19.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 20,
          src: "/daDesign/daDesignHistorias20.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 21,
          src: "/daDesign/daDesignHistorias21.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
        {
          id: 22,
          src: "/daDesign/daDesignHistorias22.webp",
          type: "image",
          alt: "Solo Agency Stories",
        },
      ],
    },
    {
      title: ["INSTAGRAM", "FEED"],
      items: [
        {
          id: 1,
          src: "/daDesign/daDesign1.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 2,
          src: "/daDesign/daDesign2.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 3,
          src: "/daDesign/daDesign3.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 4,
          src: "/daDesign/daDesign4.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 5,
          src: "/daDesign/daDesign5.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 6,
          src: "/daDesign/daDesign6.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 7,
          src: "/daDesign/daDesign7.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 8,
          src: "/daDesign/daDesign8.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 9,
          src: "/daDesign/daDesign9.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 10,
          src: "/daDesign/daDesign10.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 11,
          src: "/daDesign/daDesign11.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 12,
          src: "/daDesign/daDesign12.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 13,
          src: "/daDesign/daDesign13.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 14,
          src: "/daDesign/daDesign14.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 15,
          src: "/daDesign/daDesign15.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 16,
          src: "/daDesign/daDesign16.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 17,
          src: "/daDesign/daDesign17.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 18,
          src: "/daDesign/daDesign18.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 19,
          src: "/daDesign/daDesign19.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
        {
          id: 20,
          src: "/daDesign/daDesign20.webp",
          type: "image",
          alt: "Solo Agency Feed",
        },
      ],
    },
    {
      title: ["INSTAGRAM", "REELS"],
      items: [
        {
          id: 1,
          type: "video",
          src: "/daDesign/daDesignReel.webm",
          alt: "Solo Agency Reel",
        },
        {
          id: 2,
          type: "video",
          src: "/daDesign/daDesignReel2.webm",
          alt: "Solo Agency Reel",
        },
        {
          id: 3,
          type: "video",
          src: "/daDesign/daDesignReel3.webm",
          alt: "Solo Agency Reel",
        },
        {
          id: 4,
          type: "video",
          src: "/daDesign/daDesignReel4.webm",
          alt: "Solo Agency Reel",
        },
      ],
    },
  ];
  