export const carouselData = [
  {
    title: ["COMPAÑIA", "NATIVA"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/companiaNativa/BARRAS CN_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 2,
        type: "image",
        src: "/companiaNativa/companiaNativa1.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 3,
        type: "video",
        src: "/companiaNativa/Armado mesa Quadra_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 4,
        type: "image",
        src: "/companiaNativa/companiaNativa2.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 5,
        type: "video",
        src: "/companiaNativa/Armado exterior_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 6,
        type: "image",
        src: "/companiaNativa/companiaNativa3.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 7,
        type: "image",
        src: "/companiaNativa/companiaNativa4.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 8,
        type: "video",
        src: "/companiaNativa/Centro de mesa navideño_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 9,
        type: "image",
        src: "/companiaNativa/companiaNativa5.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 10,
        type: "video",
        src: "/companiaNativa/Saludo de fin año_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 11,
        type: "image",
        src: "/companiaNativa/companiaNativa6.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 12,
        type: "video",
        src: "/companiaNativa/Mesa navideña día_ noche_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 13,
        type: "image",
        src: "/companiaNativa/companiaNativa7.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 14,
        type: "video",
        src: "/companiaNativa/Sillas de exterior_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 15,
        type: "image",
        src: "/companiaNativa/companiaNativa8.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 16,
        type: "video",
        src: "/companiaNativa/Proceso de armado mesa Rocky_H.264.webm",
        alt: "Compañia Nativa Video",
      },
      {
        id: 17,
        type: "image",
        src: "/companiaNativa/companiaNativa9.webp",
        alt: "Compañia Nativa Image",
      },
      {
        id: 18,
        type: "video",
        src: "/companiaNativa/Saludo de fin año_H.264.webm",
        alt: "Compañia Nativa Video",
      },
    ],
  },
];
