export const carouselData = [
  {
    title: ["UNBROKEN", "FITWEAR"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/ubk/UBK_H.264.mp4",
        alt: "Unbroken Fitwear Video",
      },
      {
        id: 2,
        type: "image",
        src: "/ubk/ubk1.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 3,
        type: "image",
        src: "/ubk/ubk2.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 4,
        type: "image",
        src: "/ubk/ubk3.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 5,
        type: "image",
        src: "/ubk/ubk4.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 6,
        type: "image",
        src: "/ubk/ubk5.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 7,
        type: "image",
        src: "/ubk/ubk6.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 8,
        type: "image",
        src: "/ubk/ubk7.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 9,
        type: "image",
        src: "/ubk/ubk8.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 10,
        type: "image",
        src: "/ubk/ubk9.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 11,
        type: "image",
        src: "/ubk/ubk10.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 12,
        type: "image",
        src: "/ubk/ubk11.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 13,
        type: "image",
        src: "/ubk/ubk12.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 14,
        type: "image",
        src: "/ubk/ubk13.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 15,
        type: "image",
        src: "/ubk/ubk14.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 16,
        type: "image",
        src: "/ubk/ubk15.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 17,
        type: "image",
        src: "/ubk/ubk16.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 18,
        type: "image",
        src: "/ubk/ubk17.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 19,
        type: "image",
        src: "/ubk/ubk18.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 20,
        type: "image",
        src: "/ubk/ubk19.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 21,
        type: "image",
        src: "/ubk/ubk20.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 22,
        type: "image",
        src: "/ubk/ubk21.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 23,
        type: "image",
        src: "/ubk/ubk22.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 24,
        type: "image",
        src: "/ubk/ubk23.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 25,
        type: "image",
        src: "/ubk/ubk24.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 26,
        type: "image",
        src: "/ubk/ubk25.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 27,
        type: "image",
        src: "/ubk/ubk26.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 28,
        type: "image",
        src: "/ubk/ubk27.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 29,
        type: "image",
        src: "/ubk/ubk28.jpg",
        alt: "Unbroken Fitwear",
      },
      {
        id: 30,
        type: "image",
        src: "/ubk/ubk29.jpg",
        alt: "Unbroken Fitwear",
      },
    ],
  },
];
