export const carouselData = [
  {
    title: ["UNBROKEN", "FITWEAR"],
    items: [
      {
        id: 2,
        type: "image",
        src: "/ubk/ubk1.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 3,
        type: "image",
        src: "/ubk/ubk2.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 1,
        type: "video",
        src: "/ubk/poste UBK_H.264.webm",
        alt: "Unbroken Fitwear Video",
      },
      {
        id: 4,
        type: "image",
        src: "/ubk/ubk3.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 5,
        type: "image",
        src: "/ubk/ubk4.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 6,
        type: "image",
        src: "/ubk/ubk5.webp",
        alt: "Unbroken Fitwear",
      },
    ],
  },
  {
    title: ["", ""],
    items: [
      {
        id: 30,
        type: "video",
        src: "/ubk/UBK_H.264.webm",
        alt: "Unbroken Fitwear Video",
      },
      {
        id: 7,
        type: "image",
        src: "/ubk/ubk6.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 8,
        type: "image",
        src: "/ubk/ubk7.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 9,
        type: "image",
        src: "/ubk/ubk8.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 10,
        type: "image",
        src: "/ubk/ubk9.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 11,
        type: "image",
        src: "/ubk/ubk10.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 12,
        type: "image",
        src: "/ubk/ubk11.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 13,
        type: "image",
        src: "/ubk/ubk12.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 14,
        type: "image",
        src: "/ubk/ubk13.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 15,
        type: "image",
        src: "/ubk/ubk14.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 16,
        type: "image",
        src: "/ubk/ubk15.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 17,
        type: "image",
        src: "/ubk/ubk16.webp",
        alt: "Unbroken Fitwear",
      },
    ],
  },
  {
    title: ["", ""],
    items: [
      {
        id: 18,
        type: "image",
        src: "/ubk/ubk17.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 19,
        type: "image",
        src: "/ubk/ubk18.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 20,
        type: "image",
        src: "/ubk/ubk19.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 21,
        type: "image",
        src: "/ubk/ubk20.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 22,
        type: "image",
        src: "/ubk/ubk21.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 23,
        type: "image",
        src: "/ubk/ubk22.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 24,
        type: "image",
        src: "/ubk/ubk23.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 25,
        type: "image",
        src: "/ubk/ubk24.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 26,
        type: "image",
        src: "/ubk/ubk25.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 27,
        type: "image",
        src: "/ubk/ubk26.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 28,
        type: "image",
        src: "/ubk/ubk27.webp",
        alt: "Unbroken Fitwear",
      },
      {
        id: 29,
        type: "image",
        src: "/ubk/ubk28.webp",
        alt: "Unbroken Fitwear",
      },
    ],
  },
];
