export const carouselData = [
  {
    title: ["CAMPAIGN", "AW24"],
    maxHeight: "475px",
    items: [
      {
        id: 1,
        type: "video",
        src: "/thurman/Video campaña completa.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 2,
        type: "image",
        src: "/thurman/thurmanCampaign.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 3,
        type: "image",
        src: "/thurman/thurmanCampaign2.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 4,
        type: "image",
        src: "/thurman/thurmanCampaign3.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 5,
        type: "image",
        src: "/thurman/thurmanCampaign4.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 6,
        type: "video",
        src: "/thurman/thurmanCamp.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 7,
        type: "image",
        src: "/thurman/thurmanCampaign5.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 8,
        type: "image",
        src: "/thurman/thurmanCampaign6.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 9,
        type: "image",
        src: "/thurman/thurmanCampaign7.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 10,
        type: "video",
        src: "/thurman/thurmanCamp2.webm",
        alt: "Thurman Campaign Video",
      },
    ],
  },
  {
    title: ["", ""],
    maxHeight: "475px",
    items: [
      {
        id: 11,
        type: "image",
        src: "/thurman/thurmanCampaign8.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 12,
        type: "image",
        src: "/thurman/thurmanCampaign9.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 13,
        type: "image",
        src: "/thurman/thurmanCampaign10.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 14,
        type: "video",
        src: "/thurman/thurmanCamp3.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 15,
        type: "image",
        src: "/thurman/thurmanCampaign11.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 16,
        type: "image",
        src: "/thurman/thurmanCampaign12.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 17,
        type: "image",
        src: "/thurman/thurmanCampaign13.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 18,
        type: "video",
        src: "/thurman/thurmanCamp4.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 19,
        type: "image",
        src: "/thurman/thurmanCampaign14.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 20,
        type: "image",
        src: "/thurman/thurmanCampaign15.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 21,
        type: "image",
        src: "/thurman/thurmanCampaign16.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 22,
        type: "image",
        src: "/thurman/thurmanCampaign17.webp",
        alt: "Thurman Campaign",
      },
    ],
  },
  {
    title: ["E-", "COMMERCE"],
    items: [
      {
        id: 1,
        type: "image",
        src: "/thurman/ecom/thurmanEcom.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 2,
        type: "image",
        src: "/thurman/ecom/thurmanEcom2.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 3,
        type: "image",
        src: "/thurman/ecom/thurmanEcom3.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 4,
        type: "image",
        src: "/thurman/ecom/thurmanEcom4.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 5,
        type: "image",
        src: "/thurman/ecom/thurmanEcom5.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 6,
        type: "image",
        src: "/thurman/ecom/thurmanEcom6.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 7,
        type: "image",
        src: "/thurman/ecom/thurmanEcom7.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 8,
        type: "image",
        src: "/thurman/ecom/thurmanEcom8.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 9,
        type: "image",
        src: "/thurman/ecom/thurmanEcom9.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 11,
        type: "image",
        src: "/thurman/ecom/thurmanEcom10.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 12,
        type: "image",
        src: "/thurman/ecom/thurmanEcom11.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 13,
        type: "image",
        src: "/thurman/ecom/thurmanEcom12.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 14,
        type: "image",
        src: "/thurman/ecom/thurmanEcom13.webp",
        alt: "Thurman Campaign Video",
      },
    ],
  },
  {
    title: ["", ""],
    items: [
      {
        id: 15,
        type: "image",
        src: "/thurman/ecom/thurmanEcom14.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 16,
        type: "image",
        src: "/thurman/ecom/thurmanEcom15.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 17,
        type: "image",
        src: "/thurman/ecom/thurmanEcom16.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 18,
        type: "image",
        src: "/thurman/ecom/thurmanEcom17.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 19,
        type: "image",
        src: "/thurman/ecom/thurmanEcom18.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 20,
        type: "image",
        src: "/thurman/ecom/thurmanEcom18.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 21,
        type: "image",
        src: "/thurman/ecom/thurmanEcom19.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 22,
        type: "image",
        src: "/thurman/ecom/thurmanEcom20.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 23,
        type: "image",
        src: "/thurman/ecom/thurmanEcom21.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 24,
        type: "image",
        src: "/thurman/ecom/thurmanEcom22.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 25,
        type: "image",
        src: "/thurman/ecom/thurmanEcom22.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 26,
        type: "image",
        src: "/thurman/ecom/thurmanEcom23.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 27,
        type: "image",
        src: "/thurman/ecom/thurmanEcom24.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 28,
        type: "image",
        src: "/thurman/ecom/thurmanEcom25.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 29,
        type: "image",
        src: "/thurman/ecom/thurmanEcom26.webp",
        alt: "Thurman Campaign",
      },
    ],
  },
  {
    title: ["SOCIAL", "MEDIA"],
    items: [
      {
        id: 3,
        type: "image",
        src: "/thurman/thurmanSocialMedia.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 4,
        type: "image",
        src: "/thurman/thurmanSocialMedia2.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 5,
        type: "image",
        src: "/thurman/thurmanSocialMedia3.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 6,
        type: "image",
        src: "/thurman/thurmanSocialMedia4.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 7,
        type: "image",
        src: "/thurman/thurmanSocialMedia5.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 8,
        type: "image",
        src: "/thurman/thurmanSocialMedia6.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 9,
        type: "image",
        src: "/thurman/thurmanSocialMedia7.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 10,
        type: "image",
        src: "/thurman/thurmanSocialMedia8.webp",
        alt: "Thurman Campaign Video",
      },
      {
        id: 11,
        type: "image",
        src: "/thurman/thurmanSocialMedia9.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 12,
        type: "image",
        src: "/thurman/thurmanSocialMedia10.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 13,
        type: "image",
        src: "/thurman/thurmanSocialMedia12.webp",
        alt: "Thurman Campaign",
      },
    ],
  },
  {
    title: ["NEWS", "LETTER"],
    maxHeight: "612px",
    items: [
      {
        id: 1,
        type: "image",
        src: "/thurman/thurmanNews1.webp",
        alt: "Thurman Newsletter",
      },
      {
        id: 2,
        type: "image",
        src: "/thurman/thurmanNews2.webp",
        alt: "Thurman Newsletter",
      },
      {
        id: 4,
        type: "image",
        src: "/thurman/thurmanNews4.webp",
        alt: "Thurman Newsletter",
      },
      {
        id: 6,
        type: "image",
        src: "/thurman/thurmanNews6.webp",
        alt: "Thurman Newsletter",
      },
      {
        id: 3,
        type: "image",
        src: "/thurman/thurmanNews3.webp",
        alt: "Thurman Newsletter",
      },
      {
        id: 5,
        type: "image",
        src: "/thurman/thurmanNews5.webp",
        alt: "Thurman Newsletter",
      },
    ],
  },
];
