export const carouselData = [
  {
    title: ["THURMAN"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/thurman/Video campaña completa.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 2,
        type: "image",
        src: "/thurman/thurmanCampaign.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 3,
        type: "image",
        src: "/thurman/thurmanCampaign2.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 4,
        type: "image",
        src: "/thurman/thurmanCampaign3.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 5,
        type: "image",
        src: "/thurman/thurmanCampaign4.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 6,
        type: "video",
        src: "/thurman/thurmanCamp.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 7,
        type: "image",
        src: "/thurman/thurmanCampaign5.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 8,
        type: "image",
        src: "/thurman/thurmanCampaign6.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 9,
        type: "image",
        src: "/thurman/thurmanCampaign7.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 10,
        type: "video",
        src: "/thurman/thurmanCamp2.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 11,
        type: "image",
        src: "/thurman/thurmanCampaign8.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 12,
        type: "image",
        src: "/thurman/thurmanCampaign9.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 13,
        type: "image",
        src: "/thurman/thurmanCampaign10.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 14,
        type: "video",
        src: "/thurman/thurmanCamp3.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 15,
        type: "image",
        src: "/thurman/thurmanCampaign11.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 16,
        type: "image",
        src: "/thurman/thurmanCampaign12.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 17,
        type: "image",
        src: "/thurman/thurmanCampaign13.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 18,
        type: "video",
        src: "/thurman/thurmanCamp4.webm",
        alt: "Thurman Campaign Video",
      },
      {
        id: 19,
        type: "image",
        src: "/thurman/thurmanCampaign14.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 20,
        type: "image",
        src: "/thurman/thurmanCampaign15.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 21,
        type: "image",
        src: "/thurman/thurmanCampaign16.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 22,
        type: "image",
        src: "/thurman/thurmanCampaign17.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 23,
        type: "image",
        src: "/thurman/thurmanCampaign18.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 24,
        type: "image",
        src: "/thurman/thurmanCampaign19.webp",
        alt: "Thurman Campaign",
      },
      {
        id: 25,
        type: "image",
        src: "/thurman/thurmanCampaign20.webp",
        alt: "Thurman Campaign",
      },
    ],
  },
];
