export const carouselData = [
  {
    title: ["THURMAN"],
    items: [
      {
        id: 1,
        type: "video",
        src: "/thurman/Video campaña completa.mp4",
        alt: "Thurman Campaign Video",
      },
      {
        id: 2,
        type: "image",
        src: "/thurman/thurmanCampaign.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 3,
        type: "image",
        src: "/thurman/thurmanCampaign2.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 4,
        type: "image",
        src: "/thurman/thurmanCampaign3.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 5,
        type: "image",
        src: "/thurman/thurmanCampaign4.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 6,
        type: "video",
        src: "/thurman/thurmanCamp.mp4",
        alt: "Thurman Campaign Video",
      },
      {
        id: 7,
        type: "image",
        src: "/thurman/thurmanCampaign5.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 8,
        type: "image",
        src: "/thurman/thurmanCampaign6.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 9,
        type: "image",
        src: "/thurman/thurmanCampaign7.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 10,
        type: "video",
        src: "/thurman/thurmanCamp2.mp4",
        alt: "Thurman Campaign Video",
      },
      {
        id: 11,
        type: "image",
        src: "/thurman/thurmanCampaign8.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 12,
        type: "image",
        src: "/thurman/thurmanCampaign9.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 13,
        type: "image",
        src: "/thurman/thurmanCampaign10.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 14,
        type: "video",
        src: "/thurman/thurmanCamp3.mp4",
        alt: "Thurman Campaign Video",
      },
      {
        id: 15,
        type: "image",
        src: "/thurman/thurmanCampaign11.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 16,
        type: "image",
        src: "/thurman/thurmanCampaign12.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 17,
        type: "image",
        src: "/thurman/thurmanCampaign13.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 18,
        type: "video",
        src: "/thurman/thurmanCamp4.mp4",
        alt: "Thurman Campaign Video",
      },
      {
        id: 19,
        type: "image",
        src: "/thurman/thurmanCampaign14.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 20,
        type: "image",
        src: "/thurman/thurmanCampaign15.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 21,
        type: "image",
        src: "/thurman/thurmanCampaign16.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 22,
        type: "image",
        src: "/thurman/thurmanCampaign17.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 23,
        type: "image",
        src: "/thurman/thurmanCampaign18.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 24,
        type: "image",
        src: "/thurman/thurmanCampaign19.jpg",
        alt: "Thurman Campaign",
      },
      {
        id: 25,
        type: "image",
        src: "/thurman/thurmanCampaign20.jpg",
        alt: "Thurman Campaign",
      },
    ],
  },
];
